### ISSUE TITLE
Question : How to deal with pagination for Blog?

### ISSUE THREAD

**Issue by rajesh-h** [bovas85/nuxt-headless#29]
Hi,

I am trying to use this module with one of the existing wordpress website.

I am still confused whether i should go for SSR or Generate.

In anycase how do you manage Pagination? do you bring only few posts at a time or bring everything at once and then do the pagination.

Also bringing only chunk/few posts wil it have any impact on SEO?

Thank you for your assistance.

**Comment by bovas85** [comment]
Hey Rajesh,
You can set how many posts to return following the wordpress REST API queries and bring those in.

Regarding SSR vs Generate, if you have a lot of posts (100+) then I'd suggest using SSR instead of generate, as you will have to run the fetching for each single post on the generate (this gets easier with Nuxt v3, but not there yet)

For SEO, there should be no impact as long as you generate all your posts at compile time.

For example in nuxt.config

```

**Comment by rajesh-h** [comment]
Thank you for your response.

In case of 100+ posts can't I follow below approach?

for the first time - I generate all posts
Next time onwards I generate only those posts where their last edit/updated time is greater than last build time.

It's just a question came to my mind, i might be wrong.

**Comment by bovas85** [comment]
yes, you can do that although still very slow while generating :)

**Comment by rajesh-h** [comment]
Cool, Thank you. I will see which option to go for.

I am starting to work on this. I wanted to get away from Wordpress completely, but building admin site to add/edit posts from scratch it's a pain. so I might stay with Wordpress for my backend.

Thank you very much for all your help.
